
[en]
  title            = "The Data Behind the Story"
  LanguageName     = "English"
  weight           = 1
  codeMaxLines     = 2

[ro]
  title            = "Datele din Spatele Poveștilor" # just for the sake of showing this is possible
  introDescription = "Inginer de Date, Analist de Date, Psiholog Cognitiv și în general Om cu Păreri"
  LanguageName     = "Română"
  weight           = 2